### PR TITLE
Attempt to guess the state by IP address

### PR DESCRIPTION
**Pull request by karthikb351**
I'm not in India to test this out.
@captn3m0 @championswimmer @shreyas-satish ?

### CODE REVIEW

**Comment by captn3m0** [comment]
Site doesn't work because of mixed content warning.

**Comment by karthikb351** [comment]
@captn3m0 Bleh - switched to a service that has HTTPS support. Now?

**Comment by captn3m0** [comment]
@karthikb351 It is still enforcing UP, since that is set later after vue is initialized. Can you move the code to `created` method?

Add it in the `mp` switch/case

**Comment by siddhesh** [comment]
It's breaking but it is probably netlify's fault since my local version seems to load correctly.  It picks the correct state too.

**Pull request merged**
