### PR TITLE
update draft letter for bank with formatting and links

### PR DESCRIPTION
**Pull request by championswimmer**
Signed-off-by: Arnav Gupta <arnav@codingblocks.com>

### CODE REVIEW

**Comment by championswimmer** [comment]
Formatting has come out like this in Gmail - (screenshot from my inbox) 

screen shot 2017-12-09 at 2 14 04 am

**Comment by captn3m0** [comment]
RoundCube :cry: 

image

**Comment by jace** [comment]
Is this what it looks like when sending or receiving? Recipients may not have Gmail.

**Comment by captn3m0** [comment]
Receiving. roundcube web-UI doesn't like the formatting for some reason.

**Comment by jace** [comment]
Is it rendering the text or HTML version of the email? See the raw source. It'll help debug.

**Pull request merged**
